### ISSUE TITLE
Konsole instructions are wrong for more recent konsole

### ISSUE THREAD

**Issue by andrew-christianson** [mbadolato/iTerm2-Color-Schemes#58] opened 2015-12-04 22:00 UTC
Konsole in KF5 appears to look for colorschemes only in ~/.local/share/konsole.  Dropping the colorschemes in there works (and looks!) perfect(ly), but the instructions in the README are wrong.

**Comment by mbadolato** [comment] 2015-12-04 22:08
Thanks!   

@1player Since you added the console support, any other info/instructions you'd like to add?

**Comment by andrewcodes** [comment] 2018-01-05 17:43
Confirmed that the location that @andrew-christianson mentioned is correct on KDE 5.11.5 as well.

**Comment by mbadolato** [comment] 2018-01-06 16:31
@andrewcodes That would be fantastic, thanks!

**Comment by andrewcodes** [comment] 2018-01-15 21:37
@mbadolato created a PR: #146

**Comment by mbadolato** [comment] 2018-01-16 01:04
Thank you! merged

**Closed** 2018-01-16 01:04 UTC
